course/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah/', views.tambah),
    path('detail/<int:pk>', views.detail, name = 'detail'),
    path('hapus/<int:pk>', views.hapus, name = 'hapus')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('course/', include('course.urls')),
]

course/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    nama = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.CharField(max_length= 20)
    tahun = models.CharField(max_length=100)
    ruang = models.CharField(max_length=100)
    deskripsi = models.TextField()

main/models.py
from django.db import models

# Create your models here.

course/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Course
from .form import FormCourse
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):
    course = Course.objects.all()
    return render(request, 'course/home.html', {'course':course})

def detail(request, pk):
    kuliah = Course.objects.get(pk=pk) 
    context = {
        "detail" : kuliah,
    }
    return render(request, "course/detail.html", context)

def tambah(request):
    form = FormCourse()

    if request.method == "POST":
        form = FormCourse(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/course/")

    kuliah = Course.objects.all()

    context = {
        "form" : form,
        "listCourse" : kuliah,
    }

    return render(request, "course/tambah.html", context)
    course = Course.objects.all()

def hapus(request, pk):
    kelas = Course.objects.filter(pk=pk)
    kelas.delete()    
    return HttpResponseRedirect('/course/')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

course/templates/course/detail.html
{% extends 'base.html' %}
{% load static %}


{% block page-content %}
<h1 class="text-center">Detail Course {{detail.nama}}</h1>
<br><br>
<table class="table table-responsive table-borderless">
    <tbody>
      <tr>
        <td>Nama:</td>
        <td>{{detail.nama}}</td>
      </tr>
      <tr>
        <td>Dosen:</td>
        <td>{{detail.dosen}}</td>
      </tr>
      <tr>
        <td>Sks:</td>
        <td>{{detail.sks}}</td>
      </tr>
      <tr>
        <td>Tahun:</td>
        <td>{{detail.tahun}}</td>
      </tr>
      <tr>
        <td>Ruang:</td>
        <td>{{detail.ruang}}</td>
      </tr>
      <tr>
        <td>Deskripsi:</td>
        <td>{{detail.deskripsi}}</td>
      </tr>
    </tbody>
  </table>
{% endblock page-content %}
    

course/templates/course/home.html
{% extends 'base.html' %}
{% load static %}


{% block page-content %}
    <h1 class="text-center">Ini adalah List Mata Kuliah</h1>

    

    <div class="col-md-8 offset-md-2">
        <table class="table table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No</th>
                <th scope="col">Nama</th>
                <th scope="col">Pilihan</th>
              </tr>
            </thead>
            <tbody>
              
            {% for co in course %}  
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{co.nama}}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'course:detail' pk=co.pk %}">Detail</a>
                    <a class="btn btn-danger" href="{% url 'course:hapus' pk=co.pk %}">Hapus</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
{% endblock page-content %}
    

course/templates/course/tambah.html
{% extends 'base.html' %}
{% load static %}


{% block page-content %}
    <h1 class="text-center">Menambah Course</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-md-12 text-center">
            <input class="btn btn-success" type="submit" value="Tambah">
        </div>
    </form>

{% endblock page-content %}
    

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block page-content %}

<!-- Page Content-->
<div class="container-fluid p-0">
  <!-- About-->
  <section class="resume-section" id="about">
      <div class="resume-section-content">
          <h1 class="mb-0">
              Sultan
              <span class="text-primary">Nusantara</span>
          </h1>
          <div class="subheading mb-5">
              3542 Kenanga Raya · Bekasi, CO 80810 · (317) 585-8468 ·
              <a href="mailto:name@email.com">nusantarasulltan@email.com</a>
          </div>
          <p class="lead mb-5">Saya senang sekali mencoba hal-hal baru dan mempelajari berbagai ilmu terutama di bidang IT dan Bisnis. Saat ini saya sedang mempelajari PPW atau Perancangan dan Pengembangan Website. Semoga saya bisa mengerjakannya dengan baik.</p>
          <div class="social-icons">
              <a class="social-icon" href="https://www.linkedin.com/in/sultan-daffa-nusantara-b1a7821a5"><i class="fab fa-linkedin-in"></i></a>
              <a class="social-icon" href="https://github.com/SultanDaffaN"><i class="fab fa-github"></i></a>
              <a class="social-icon" href="https://twitter.com/Sulltannusanta1?s=09"><i class="fab fa-twitter"></i></a>
              <a class="social-icon" href="https://www.facebook.com/nusantarasulltan.nusantarasulltan"><i class="fab fa-facebook-f"></i></a>
          </div>
      </div>
  </section>
  <hr class="m-0" />
  <!-- Experience-->
  <section class="resume-section" id="experience">
      <div class="resume-section-content">
          <h2 class="mb-5">Experience</h2>
          <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
              <div class="flex-grow-1">
                  <h3 class="mb-0">Senior Web Developer</h3>
                  <div class="subheading mb-3">Intelitec Solutions</div>
                  <p>Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">March 2025 - Present</span></div>
          </div>
          <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
              <div class="flex-grow-1">
                  <h3 class="mb-0">Web Developer</h3>
                  <div class="subheading mb-3">Intelitec Solutions</div>
                  <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">December 2022 - March 2025</span></div>
          </div>
          <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
              <div class="flex-grow-1">
                  <h3 class="mb-0">Junior Web Designer</h3>
                  <div class="subheading mb-3">Shout! Media Productions</div>
                  <p>Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">July 2021 - December 2023</span></div>
          </div>
          <div class="d-flex flex-column flex-md-row justify-content-between">
              <div class="flex-grow-1">
                  <h3 class="mb-0">Web Design Intern</h3>
                  <div class="subheading mb-3">Shout! Media Productions</div>
                  <p>Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">September 2020 - June 2021</span></div>
          </div>
      </div>
  </section>
  <hr class="m-0" />
  <!-- Education-->
  <section class="resume-section" id="education">
      <div class="resume-section-content">
          <h2 class="mb-5">Education</h2>
          <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
              <div class="flex-grow-1">
                  <h3 class="mb-0">University of Indonesia</h3>
                  <div class="subheading mb-3">Bachelor of Computer Science</div>
                  <div>Information System - Web Development Track</div>
                  <p>GPA: 3.23</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">August 2019 - May 2022</span></div>
          </div>
          <div class="d-flex flex-column flex-md-row justify-content-between">
              <div class="flex-grow-1">
                  <h3 class="mb-0">Albinaa Islamic School</h3>
                  <div class="subheading mb-3">Senior High School</div>
                  <p>GPA: 3.56</p>
              </div>
              <div class="flex-shrink-0"><span class="text-primary">August 2016 - May 2019</span></div>
          </div>
      </div>
  </section>
  <hr class="m-0" />
  <!-- Skills-->
  <section class="resume-section" id="skills">
      <div class="resume-section-content">
          <h2 class="mb-5">Skills</h2>
          <div class="subheading mb-3">Programming Languages & Tools</div>
          <ul class="list-inline dev-icons">
              <li class="list-inline-item"><i class="fab fa-html5"></i></li>
              <li class="list-inline-item"><i class="fab fa-css3-alt"></i></li>
              <li class="list-inline-item"><i class="fab fa-js-square"></i></li>
              <li class="list-inline-item"><i class="fab fa-angular"></i></li>
              <li class="list-inline-item"><i class="fab fa-react"></i></li>
              <li class="list-inline-item"><i class="fab fa-node-js"></i></li>
              <li class="list-inline-item"><i class="fab fa-sass"></i></li>
              <li class="list-inline-item"><i class="fab fa-less"></i></li>
              <li class="list-inline-item"><i class="fab fa-wordpress"></i></li>
              <li class="list-inline-item"><i class="fab fa-gulp"></i></li>
              <li class="list-inline-item"><i class="fab fa-grunt"></i></li>
              <li class="list-inline-item"><i class="fab fa-npm"></i></li>
          </ul>
          <div class="subheading mb-3">Workflow</div>
          <ul class="fa-ul mb-0">
              <li>
                  <span class="fa-li"><i class="fas fa-check"></i></span>
                  Mobile-First, Responsive Design
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-check"></i></span>
                  Cross Browser Testing & Debugging
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-check"></i></span>
                  Cross Functional Teams
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-check"></i></span>
                  Agile Development & Scrum
              </li>
          </ul>
      </div>
  </section>
  <hr class="m-0" />
  <!-- Interests-->
  <section class="resume-section" id="interests">
      <div class="resume-section-content">
          <h2 class="mb-5">Interests</h2>
          <p>Selain mencoba senang dalam menjalani perkuliahan ini, saya tertarik dengan berbagai bidang lain, yaitu bisnis, psikologi, dan filsafat. Adapun olahraga, saya sangat menyukai beladiri dan tennis meja. Saya juga bercita-cita membangun usaha sendiri.</p>
          <p class="mb-0">Ketika di rumah, saya sangat menyukai sekali menonton film bergenre misteri, sci-fi, action, dan thriller. Saya juga sangat menyukai membaca waktu jika ada waktu. Buku yang saya sukai berkaitan dengan bisnis, psikologi, dan Pengembangan diri.</p>
      </div>
  </section>
  <hr class="m-0" />
  <!-- Awards-->
  <section class="resume-section" id="awards">
      <div class="resume-section-content">
          <h2 class="mb-5">Awards & Certifications</h2>
          <ul class="fa-ul mb-0">
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  Google Analytics Certified Developer
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  Mobile Web Specialist - Google Certification
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  1
                  <sup>st</sup>
                  Place - University of Colorado Boulder - Emerging Tech Competition 2009
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  1
                  <sup>st</sup>
                  Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  2
                  <sup>nd</sup>
                  Place - University of Colorado Boulder - Emerging Tech Competition 2008
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  1
                  <sup>st</sup>
                  Place - James Buchanan High School - Hackathon 2006
              </li>
              <li>
                  <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                  3
                  <sup>rd</sup>
                  Place - James Buchanan High School - Hackathon 2005
              </li>
          </ul>
      </div>
  </section>
</div>
  
{% endblock page-content %}
  

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Resume - sultan Daffa Nusantara</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/crown-logo.png' %}" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body>
  {% include 'snippets/navbar.html' %}

  
  {% block page-content %}
  {% endblock page-content %}
    

<!-- Bootstrap core JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

templates/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Sultan Nusantara</span>
        <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/MyPicture.png' %}" alt="" /></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#about">About</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#experience">Experience</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#education">Education</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#skills">Skills</a></li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Course
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/course/">List</a>
                  <a class="dropdown-item" href="/course/tambah/">Add</a>
                </div>
              </li>        
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#interests">Interests</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/#awards">Awards</a></li>
        </ul>
    </div>
</nav>